version: "3.8"

services:
  redis:
    image: redis:6.0-alpine
    container_name: db-redis-offer-banner
    ports:
      - 6379:6379
    networks:
      - vittmitra
    volumes:
      - ./src/offer_banner/conf/:/etc/redis/

  helper:
    build: ./helper
    container_name: ms-helper
    networks:
      - vittmitra
    depends_on:
      - redis

  offer-banner:
    build: ./src/offer_banner
    container_name: ms-offer-banner
    networks:
      - vittmitra
    depends_on:
      - redis
      - helper

  frontend:
    build: ./src/frontend
    container_name: ms-frontend
    networks:
      - vittmitra
    depends_on:
      - redis
      - helper
      - offer-banner

networks:
  vittmitra:
    driver: bridge
