version: "3.8"

services:
  solr:
    image: solr
    ports:
      - "8983:8983"
    # volumes:
    #   - data:/var/solr
    command:
      - solr-precreate
      - gettingstarted
# volumes:
#   data:
# services:
#   solr:
#     image: solr:9-slim
#     container_name: solr-searcher
#     ports:
#       - 8983:8983
#     environment:
#       - ZK_HOST=zoo:2181
#     networks:
#       - vittmitra
#     depends_on:
#       - zoo

#   # zoo:
#   #   image: zookeeper:3.8
#   #   container_name: zoo
#   #   restart: always
#   #   hostname: zoo
#   #   ports:
#   #     - 2181:2181
#   #     - 7000:7000
#   #   environment:
#   #     - ZOO_MY_ID: 1
#   #     - ZOO_SERVERS: server.1=zoo:2888:3888;2181
#   #   networks:
#   #     - vittmitra

#   zoo:
#     image: zookeeper:3.9
#     container_name: zoo
#     # restart: always
#     # hostname: zoo
#     ports:
#       - 2181:2181
#       # - 7000:7000
#     environment:
#       # - ZOO_MY_ID: 1
#       # - ZOO_SERVERS: server.1=zoo:2888:3888;2181
#       - ZOO_4LW_COMMANDS_WHITELIST: "mntr,conf,ruok"
#     networks:
#       - vittmitra

# networks:
#   vittmitra:
#     driver: bridge
