services:
  mongodb:
    # image: mongo:4.2.2  # Vulnerable version
    image: mongo:7.0  # Vulnerable version
    container_name: mongodb-vulnerable
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - mongo-network
    volumes:
      - mongo_data:/data/db
      - ./mongo.conf:/etc/mongod.conf 
    command: ["mongod", "--config", "/etc/mongod.conf"]

  # Test client container to try connecting to MongoDB
  test-client:
    image: mongo:7.0  # MongoDB client image
    container_name: mongo-test-client
    depends_on:
      - mongodb
    networks:
      - mongo-network
    entrypoint: >
      bash -c "
        echo 'Testing MongoDB connection';
        sleep 10;
        mongo --host mongodb-vulnerable --port 27017 -u root -p password --eval 'db.runCommand({ connectionStatus: 1 })';
        echo 'Connection test complete. Keeping the container running...';
        tail -f /dev/null
      "

networks:
  mongo-network:
    driver: bridge

volumes:
  mongo_data:
    driver: local